### ISSUE TITLE
Can't change output mixer volume

### ISSUE THREAD

**Issue by MrToWy** [Professor-Melvin/ElgatoWaveLinkSDK#1]
When calling this:
`var newSetting = await client.SetOutputMixer(1, false, 1, true);`

The response is:
```
{
    "id": 10,
    "jsonrpc": "2.0",
    "result": {
        "isLocalOutMuted": false,
        "isStreamOutMuted": false,
        "localVolumeOut": 0,
        "streamVolumeOut": 0
    }
}
```

Expected response:
```
{
    "id": 10,
    "jsonrpc": "2.0",
    "result": {
        "isLocalOutMuted": false,
        "isStreamOutMuted": true,
        "localVolumeOut": 1,
        "streamVolumeOut": 1
    }
}
```

**Comment by MrToWy** [comment]
I think that it might be something related to StreamJsonRpc.  
Used your code without the StreamJsonRpc and it works perfectly:

```
using (var ws = new WebSocket($"ws://{"localhost"}:{1824}/"))
            {
                ws.OnMessage += (sender, e) =>
                    Console.WriteLine(e.Data);

                ws.Connect();

                ws.Send("{    \"id\": 3,    \"jsonrpc\": \"2.0\",    \"method\": \"setOutputMixer\",    \"params\": {                    \"isLocalOutMuted\": true, \"isStreamOutMuted\": true, \"localVolumeOut\": 33, \"streamVolumeOut\": 44    }            }            ");
                Console.ReadKey(true);
            }
```

Same goes for SetMonitorMixOutput:
`ws.Send("{    \"id\": 3,    \"jsonrpc\": \"2.0\",    \"method\": \"setMonitorMixOutput\",    \"params\": {                    \"monitorMix\": \"" + (_useSpeaker ? speaker : headphones) + "\"    }            }            ");`

**Comment by Professor-Melvin** [comment]
Oh cool!
I'll take a look at this tonight!
Thanks for testing this out

**Comment by oddbear** [comment]
Awesome, and great work. Hope you figure it out.
I started on something similar, but did not have the time for it. So it was really nice to find this repo.

**Comment by Professor-Melvin** [comment]
So I dropped the use of StreamJsonRpc, couldn't figure out what it was doing wrong that set commands werent working

Latest push isn't complete everything except the switchMonitoring and setInputMixer commands work.

I'm in the middle of moving so I didn't have a lot of time to look through the stream deck plugin to see how they're expecting the setInputMixer command to work.
And for what ever reason I can use the switchMonitoring comamnd to go to stream mix but not monitor mix, a bit odd but I'm assuming it's something small I just can't see right now

I'm in the middle of moving, so I'll have another sit down during the week and read through the stream deck plugin to see what is different about those two commands

**Comment by Professor-Melvin** [comment]
Closing this as it was the rpc library blocking the use of SetOutputMixer
