### ISSUE TITLE
Wrong json structure?

### ISSUE THREAD

**Issue by oddbear** [Professor-Melvin/ElgatoWaveLinkSDK#10]
I try to use your SDK for building a Loupedeck plugin.
It's awesome, but I had to do some changes: https://github.com/oddbear/ElgatoWaveLinkSDK/tree/net472

I have found some small bugs. I am on 1.5.0.2889 of the Wave Link software, and it seems like a JSON might have changed for the `channelsChanged` event. At my end the event is different, the list is in a `channel property` in the json. These makes the Deserialization fail.

I changed it to:
```csharp
case "channelsChanged":
    obj = JsonConvert.DeserializeObject<List<ChannelInfo>>(baseObject.Obj?["channels"]?.ToString());
```

This seems to work.
Also if a deserialization of an event fails, the whole receive routine will stop working, but this might be by design?

All my changes to make it work:
- changed to target .net 4.7.2 (limitations of the Loupedeck)
- Fixed issue with deserialization `return JsonConvert.DeserializeObject<OutT>(reply.Result?.ToString());`, this seems to be fixed in your UI branch.
- Issue explained over.

Oddbjørn

**Comment by Professor-Melvin** [comment]
Hey, thanks for giving feedback
Really appreciate it

Interesting you've Json reply is different, I thought I had the latest installed and mine isn't like that
I might have to look at making it parse the json differently based on what version it is
But I'll have a look at this after work

Not entirely on purpose when I wrote it tbh
If it gives you an exception outside the library (Not sure how you'd receive that), then great as it'll let you now about versioning issues
But in the long run I should probably just have some sort version check in the library

And yeah, I'm creating a wpf test app that looks like the WaveLink as both a sample project but also just for some fun myself
I've noticed a few issues and things I want to do better while doing that, so I'm hoping to merge that to main soon

**Comment by Professor-Melvin** [comment]
Oh, also forgot to say
I do plan to add support for Framework by seeing if I can change the project over to DotNet standard

**Comment by oddbear** [comment]
I receive the Exceptions through the Events in Visual Studio.

I also found another bug that was interesting.
To reproduce, I close Wave Link, start it up again, then try to Connect to the client. It throws this exception:
Event Type Moniker	Event	Time	Duration	Thread
	Exception thrown: 'ElgatoWaveSDK.Models.ElgatoException' in mscorlib.dll ("Looped through possible ports 2 times and couldn't connect [1824-1834]") Exception thrown: 'ElgatoWaveSDK.Models.ElgatoException' in mscorlib.dll ("Looped through possible ports 2 times and couldn't connect [1824-1834]") Hyperlink: Activate Historical Debugging	41,291.06s		[3808] Worker Thread 

However, if I run Disconnect, then Connects again, it does not.

**Comment by oddbear** [comment]
A little fallow up question on this one. What of the Wave devices do you use, the XLR or one of the microphones.
I am having the XLR, so if it's the same, then don't mind. But if it's one of the microphones, they might have done something different there.

**Comment by Professor-Melvin** [comment]
I've done some work on the exceptions from the receive thread and added an exception event that you can listen to
And I must have been a version behind as when I went to check, I also had the list in a "channel" element

I have the Wave:3, but as I also have the channel element, it must have just been an update to their websocket that I missed
I also don't have Unit tests for the events atm, so need to get that fixed

**Comment by oddbear** [comment]
Today the Wave:1 was on sale... so now I also have one of those to test with. 😂 So with my Wave XLR, we can try all of the devices with the SDK.

**Comment by Professor-Melvin** [comment]
Oh amazing! V helpful to look and see if there are any differences with any of the devices in the future
I can't imagine they would do that, seems like extra work on their part

Interesting they don't support multiple devices like they have with the StreamDeck, might be driver limitation though

**Comment by oddbear** [comment]
With the Exception events, I think I can send the plugin for validation to the Loupedeck markedplace. Is there a release of the NuGet planned soon, or should I just build my own?

Might also create a Touch Portal plugin for this, as [the only one I found](https://github.com/mattatcha/touchportal_elgato-wave) has no release and has not been updated in two years.

**Comment by Professor-Melvin** [comment]
Hey, sorry for the long wait
In my head I was going to get the sample app done and then release it all but I just haven't had the time

I've tidied it up and I'm going to go ahead without the app, it isn't really needed 
More was just fun to make and test with lol

**Comment by Professor-Melvin** [comment]
@oddbear 
Okay, I'm about to lose my will to live trying to figure out why the unit tests won't pass on the github actions pipeline but can work perfectly locally
So I'll tidy the weird logging stuff I've added in this evening, remove the test step from the pipeline and have this released this evening for you

Again sorry for the wait, never thought the tests would act like this

**Comment by oddbear** [comment]
That's awesome, and really thanks for all your work.
Maybe I can look at the tests and try it out in a forked repository. I am a little busy right now, so it might not be before after the weekend though.

**Comment by Professor-Melvin** [comment]
I've just kicked off the beta release to NuGet, and if you get a chance to look at the tests amazing
If not, I'm gonna try force my way through it at some point

Don't wanna push it past beta till I know it's 100 percent working and/or I get the tests working lmao
I've tested stuff locally myself and it seems to all be fine so still very confused about the why the tests just decided to stop working

**Comment by oddbear** [comment]
It seems to work perfect... ❤🎉 after some changes... But that is most likely Loupedecks fault (as that's the application I try to use it with).

I think the Websocket.Client dependency is not needed, and I have some issues with the NuGet, but if I compile it myself and excludes this (or removes it), it seems to work perfect.

I am not sure if that is the one dependency that causes this, as this is a common dependency hell issue in Loupedeck at this point (should be fixes very soon though). So no need to make a new package or anything just for this, but it could be ok to remove from project if not needed for the future.

I will be testing it as a part of my daily workflow... and again, thanks.

**Comment by Professor-Melvin** [comment]
Glad to hear! 

Yeah, I must have missed that when changing around the websocket stuff
I'll move that with whatever my fix is for the tests|
So the full release will have that removed
