### ISSUE TITLE
Support Framework

### ISSUE THREAD

**Issue by Professor-Melvin** [Professor-Melvin/ElgatoWaveLinkSDK#11]
Change library to use standard to allow for framework support

**Comment by oddbear** [comment]
Seems like you set it to 2.1...
Only 2.0 is compatible with .Net framework:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

**Comment by Professor-Melvin** [comment]
God damn it!
